# Generated by Django 5.0.7 on 2024-08-03 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_deletedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedtask',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
